/*
 * ZXC - High-performance lossless compression
 *
 * Copyright (c) 2025-2026 Bertrand Lebonnois and contributors.
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Valid-vector generator.
 *
 * Rebuilds conformance/valid/<name>.zxc from the recipe in valid_cases.h, by
 * recompressing each committed <name>.expected with the options that vector is
 * declared with.
 *
 * Why this tool exists: before it, the recipe lived nowhere. The corpus was
 * regenerated by hand at the v6, v7 and v8 bumps, so reproducing it depended on
 * remembering which level, block size and flags each vector used - and a
 * regeneration with different options would silently invalidate README.md's
 * coverage table without failing anything.
 *
 * Usage:
 *   zxc_valid_gen [<vectors-dir>]    # defaults to "conformance/valid"
 *
 * The .expected plaintexts and the .zxd dictionaries are inputs, never written:
 * they are the published reference third-party decoders check against.
 *
 * Run it after a format bump, then re-run the conformance suite and review the
 * diff: any change here is a wire-format change and must be intentional.
 */

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#ifdef _MSC_VER
#include <io.h>
#include <share.h>
#endif

#include "../include/zxc_buffer.h"
#include "../include/zxc_dict.h"
#include "../include/zxc_error.h"
#include "valid_cases.h"

/* Owner-only (0600) binary write, mirroring tests/format/gen_golden.c: avoids
 * fopen()'s world-writable 0666 default flagged by CodeQL. */
static FILE* open_restricted_wb(const char* path) {
#ifdef _MSC_VER
    int fd = -1;
    _sopen_s(&fd, path, _O_CREAT | _O_WRONLY | _O_TRUNC | _O_BINARY, _SH_DENYNO,
             _S_IREAD | _S_IWRITE);
    return fd >= 0 ? _fdopen(fd, "wb") : NULL;
#else
    const int fd = open(path, O_CREAT | O_WRONLY | O_TRUNC, S_IRUSR | S_IWUSR);
    return fd >= 0 ? fdopen(fd, "wb") : NULL;
#endif
}

static uint8_t* read_file(const char* path, size_t* out_size) {
    FILE* f = fopen(path, "rb");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        return NULL;
    }
    const long len = ftell(f);
    if (len < 0 || fseek(f, 0, SEEK_SET) != 0) {
        fclose(f);
        return NULL;
    }
    /* +1 so a zero-length vector still yields a non-NULL pointer. */
    uint8_t* buf = (uint8_t*)malloc((size_t)len + 1);
    if (buf && len > 0 && fread(buf, 1, (size_t)len, f) != (size_t)len) {
        free(buf);
        buf = NULL;
    }
    fclose(f);
    if (buf) *out_size = (size_t)len;
    return buf;
}

static int write_file(const char* path, const uint8_t* data, size_t size) {
    FILE* f = open_restricted_wb(path);
    if (!f) {
        fprintf(stderr, "  cannot open %s for writing\n", path);
        return -1;
    }
    if (size && fwrite(data, 1, size, f) != size) {
        fprintf(stderr, "  short write to %s\n", path);
        fclose(f);
        return -1;
    }
    fclose(f);
    return 0;
}

static int output_dir_is_safe(const char* dir) {
    return dir[0] != '\0' && strstr(dir, "..") == NULL;
}

/* Regenerate one vector. Returns 0 on success. */
static int generate(const char* dir, const valid_case_t* vc) {
    char path[1024];
    int rc = -1;

    snprintf(path, sizeof path, "%s/%s.expected", dir, vc->name);
    size_t in_size = 0;
    uint8_t* input = read_file(path, &in_size);
    if (!input) {
        fprintf(stderr, "  FAIL %s: cannot read %s\n", vc->name, path);
        return -1;
    }

    /* The .zxd carries both the dictionary content and its shared literal
     * Huffman table; both take part in the dict_id the archive binds to. */
    zxc_compress_opts_t opts = vc->opts;
    uint8_t* dict_buf = NULL;
    if (vc->dict) {
        snprintf(path, sizeof path, "%s/%s", dir, vc->dict);
        size_t dict_file_size = 0;
        dict_buf = read_file(path, &dict_file_size);
        if (!dict_buf) {
            fprintf(stderr, "  FAIL %s: cannot read %s\n", vc->name, path);
            free(input);
            return -1;
        }
        if (zxc_dict_load(dict_buf, dict_file_size, &opts.dict, &opts.dict_size, &opts.dict_huf,
                          NULL) != 0) {
            fprintf(stderr, "  FAIL %s: %s is not a valid dictionary\n", vc->name, path);
            free(dict_buf);
            free(input);
            return -1;
        }
    }

    const size_t cap = (size_t)zxc_compress_bound(in_size) + 4096;
    uint8_t* out = (uint8_t*)malloc(cap);
    if (!out) {
        fprintf(stderr, "  FAIL %s: out of memory\n", vc->name);
    } else {
        const int64_t csize = zxc_compress(input, in_size, out, cap, &opts);
        if (csize <= 0) {
            fprintf(stderr, "  FAIL %s: compress -> %s\n", vc->name, zxc_error_name((int)csize));
        } else {
            snprintf(path, sizeof path, "%s/%s.zxc", dir, vc->name);
            if (write_file(path, out, (size_t)csize) == 0) {
                printf("  wrote %-20s %8lld bytes  (level %d, block %zu KB%s%s)\n", vc->name,
                       (long long)csize, vc->opts.level, vc->opts.block_size / 1024u,
                       vc->opts.checksum_enabled ? ", checksum" : "",
                       vc->opts.seekable ? ", seekable" : "");
                rc = 0;
            }
        }
    }

    free(out);
    free(dict_buf);
    free(input);
    return rc;
}

int main(int argc, char** argv) {
    const char* dir = (argc > 1) ? argv[1] : "conformance/valid";
    if (!output_dir_is_safe(dir)) {
        fprintf(stderr, "refusing output directory '%s': must not be empty or contain '..'\n", dir);
        return EXIT_FAILURE;
    }

    printf("Regenerating %zu valid vectors in %s/\n", (size_t)VALID_CASE_COUNT, dir);

    int failures = 0;
    for (size_t i = 0; i < VALID_CASE_COUNT; i++)
        if (generate(dir, &VALID_CASES[i]) != 0) failures++;

    if (failures) {
        fprintf(stderr, "Generation FAILED (%d error(s)).\n", failures);
        return 1;
    }
    printf("Done. Re-run the conformance suite and review the diff.\n");
    return 0;
}
