/*
 * ZXC - High-performance lossless compression
 *
 * Copyright (c) 2025-2026 Bertrand Lebonnois and contributors.
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Recipe for the valid conformance vectors.
 *
 * This header is the single source of truth for how every
 * conformance/valid/<name>.zxc was produced. It exists because the recipe used
 * to live nowhere: the corpus was regenerated by hand at the v6, v7 and v8
 * format bumps, so reproducing it depended on remembering the options. A bump
 * that regenerated the corpus with different options would silently invalidate
 * the coverage table in README.md - the vector named "level5" would stop
 * testing level 5, and nothing would fail.
 *
 * The INPUT of each vector is its committed <name>.expected file, not a
 * generator. That is deliberate and differs from tests/format/golden_cases.h:
 * this corpus is published for third-party decoder implementations, which need
 * the reference output to compare against (see README.md), so .expected must
 * stay committed. Keeping it as the input too means there is exactly one copy
 * of the plaintext, and it cannot drift from what decoders are checked against.
 *
 * Dictionary vectors reference a committed .zxd for the same reason: the
 * training samples are not part of the corpus.
 *
 * Every field is stated explicitly, including the ones that match the library
 * defaults today. A default that changes must show up as a corpus diff, not
 * silently re-cut the vectors.
 */

#ifndef ZXC_VALID_CASES_H
#define ZXC_VALID_CASES_H

#include <stddef.h>

#include "../include/zxc_opts.h"

#define VC_KB(n) ((size_t)(n) * 1024u)
#define VC_MB(n) ((size_t)(n) * 1024u * 1024u)

typedef struct {
    const char* name; /* basename, no extension: <name>.expected -> <name>.zxc */
    const char* dict; /* .zxd basename in the same directory, or NULL */
    zxc_compress_opts_t opts;
} valid_case_t;

/* The corpus, grouped as in README.md "Vector coverage". */
static const valid_case_t VALID_CASES[] = {
    /* Basic: degenerate sizes and full byte-value coverage. */
    {"empty", NULL, {.level = 3, .block_size = VC_KB(512)}},
    {"one_byte", NULL, {.level = 3, .block_size = VC_KB(512)}},
    {"all_256_values", NULL, {.level = 3, .block_size = VC_KB(512)}},
    {"all_zeros_4k", NULL, {.level = 3, .block_size = VC_KB(512)}},
    {"all_zeros_64k", NULL, {.level = 3, .block_size = VC_KB(512)}},

    /* Text: compressible input, with and without checksums. */
    {"text_1k", NULL, {.level = 3, .block_size = VC_KB(512)}},
    {"text_1k_checksum", NULL, {.level = 3, .block_size = VC_KB(512), .checksum_enabled = 1}},
    {"text_64k", NULL, {.level = 3, .block_size = VC_KB(512)}},

    /* Random: incompressible, must land in RAW blocks. */
    {"random_256", NULL, {.level = 3, .block_size = VC_KB(512)}},
    {"random_4k", NULL, {.level = 3, .block_size = VC_KB(512)}},
    {"random_4k_checksum", NULL, {.level = 3, .block_size = VC_KB(512), .checksum_enabled = 1}},
    {"random_64k", NULL, {.level = 3, .block_size = VC_KB(512)}},

    /* Match patterns: long matches, short matches, maximum offset distance. */
    {"long_match_64k", NULL, {.level = 3, .block_size = VC_KB(512)}},
    {"long_match_checksum", NULL, {.level = 3, .block_size = VC_KB(512), .checksum_enabled = 1}},
    {"short_matches_4k", NULL, {.level = 3, .block_size = VC_KB(512)}},
    {"max_offset_128k", NULL, {.level = 3, .block_size = VC_KB(512)}},

    /* Compression levels: same input at each level. Several of these currently
     * produce identical archives (levels 1/2 and 3/4 coincide on this input);
     * the level recorded here is the one the vector is named for, so the
     * coverage survives an encoder change that separates them again. */
    {"text_64k_level1", NULL, {.level = 1, .block_size = VC_KB(512)}},
    {"text_64k_level2", NULL, {.level = 2, .block_size = VC_KB(512)}},
    {"text_64k_level3", NULL, {.level = 3, .block_size = VC_KB(512)}},
    {"text_64k_level4", NULL, {.level = 4, .block_size = VC_KB(512)}},
    {"text_64k_level5", NULL, {.level = 5, .block_size = VC_KB(512)}},
    {"text_64k_level6", NULL, {.level = 6, .block_size = VC_KB(512)}},

    /* Level 7 (ULTRA): PivCo literal section, enc_lit = 2. */
    {"glo_pivco_wide_l7", NULL, {.level = 7, .block_size = VC_KB(512)}},

    /* Block-size variants. */
    {"text_8k_bs4k", NULL, {.level = 3, .block_size = VC_KB(4)}},
    {"text_64k_bs2m", NULL, {.level = 3, .block_size = VC_MB(2)}},

    /* Checksums on a compressible payload. */
    {"zeros_4k_checksum", NULL, {.level = 3, .block_size = VC_KB(512), .checksum_enabled = 1}},

    /* Multi-block: 4 KB blocks over a 64 KB input. */
    {"multiblock_text", NULL, {.level = 3, .block_size = VC_KB(4)}},
    {"multiblock_mixed", NULL, {.level = 3, .block_size = VC_KB(4)}},

    /* Seekable: seek table appended, with and without checksums. */
    {"seekable_1block", NULL, {.level = 3, .block_size = VC_KB(512), .seekable = 1}},
    {"seekable_4blocks", NULL, {.level = 3, .block_size = VC_KB(8), .seekable = 1}},
    {"seekable_checksum",
     NULL,
     {.level = 3, .block_size = VC_KB(512), .checksum_enabled = 1, .seekable = 1}},

    /* Dictionary: the .zxd carries the content and its shared Huffman table. */
    {"dict_http", "dict_http.zxd", {.level = 3, .block_size = VC_KB(512), .checksum_enabled = 1}},
    {"dict_seekable_l7",
     "dict_text.zxd",
     {.level = 7, .block_size = VC_KB(512), .checksum_enabled = 1, .seekable = 1}},
};

#define VALID_CASE_COUNT (sizeof(VALID_CASES) / sizeof(VALID_CASES[0]))

#endif /* ZXC_VALID_CASES_H */
